### ISSUE TITLE
Convert $queryprune modifier to $removeparam

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/tsurlfilter#3]
It seems that uBlock Origin has added support for `queryprune` modifier - https://github.com/gorhill/uBlock/commit/1e2eb037e5b4754feb4a40519951b3e7a73d545d, so I think that it would be a good idea to convert it to `removeparam`.

**Comment by ameshkov** [comment]
I'll be keeping an eye on that feature. It looks a little bit more limited than $removeparam so I guess when the work is done, converting it won't be that complicated.

**Comment by gorhill** [comment]
> It looks a little bit more limited than `$removeparam`

What do you have in mind when you say this?

**Comment by ameshkov** [comment]
Check the spec: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#removeparam-modifier

Essentially the same, but less limitations are imposed on the rule syntax (supports any URL, regexes)

**Comment by gorhill** [comment]
I did check before writing my comment above and I still do not it.

> supports any URL

I don't understand this part, there is no restriction regarding URL for `queryprune=`.

> regexes

The values for `queryprune=` are implicitly regex, hence why surrounding `/` are not needed. The only difference with regexes is to use `|` for anchoring to start and end because I do not want to have to deal with the ambiguity of `$` given that is already being used as a filter option separator.

Note that `queryprune=` supports filtering parameters by either parameter name, paramater value, or both since the regex is tested against the string `param=value`.

**Comment by ameshkov** [comment]
I guess this pipe char is what confused me. Anyways, the closer they are, the better, we'll either fully support it or convert to $removeparam internally, depends on how interchangeable they are.

**Comment by gorhill** [comment]
I cannot see `removeparam` being used in many AdGuard filter lists I've looked at -- beside unmatched broad exceptions in AdGuard Base. Is this a new filter option?

**Comment by ameshkov** [comment]
Yep, it's been added just recently and used internally in the Stealth Mode module (it has "remove tracking parameters" setting).

**Comment by krystian3w** [comment]
Maybe need test on Polish Onet portals:

https://github.com/AdguardTeam/AdguardFilters/blob/2fb36af53d78ac966b1de303bfac4c1d7f9e8f10/EnglishFilter/sections/whitelist_stealth.txt#L477-L479

AdGuard was generated endless refreshing loop.

**Comment by DandelionSprout** [comment]
I've submitted a vice-versa report to uBO at https://github.com/uBlockOrigin/uBlock-issues/issues/1356, since there's now active usage cases of `$removeparam` in Dandelion Sprout's Nordic Filters, and of `$queryprune` in Frellwit's Swedish Filter.

**Comment by ameshkov** [comment]
@Mizzick we may need to implement some changes (see this: https://github.com/AdguardTeam/CoreLibs/issues/1384).
