### ISSUE TITLE
uBlock HTML filters won't converted properly

### ISSUE THREAD

**Issue by scripthunter7** [AdguardTeam/tsurlfilter#55]
```typescript
import { RuleConverter, RuleFactory, CosmeticRule } from '@adguard/tsurlfilter';

const testRules: string[] = [
    // These uBO HTML rules detected as "simple element hiding" rules as they are not properly converted to AG syntax:
    // https://github.com/uBlockOrigin/uAssets/blob/fb5490d37ac45ef4c0d411462ffe2b08e1b3af97/filters/filters-2022.txt#L72
    'entrepelis.org,mangagenki.me##^script[data-cfasync]:has-text(h=decodeURIComponent)',
    // https://github.com/uBlockOrigin/uAssets/blob/fb5490d37ac45ef4c0d411462ffe2b08e1b3af97/filters/filters-2022.txt#L2298
    'mangaraw.org##^script[data-cfasync]:has-text(D4zz.)',
    // https://github.com/hufilter/hufilter-dev/blob/master/sections/ublock-specific.txt#L9
    '24.hu##^body > script:has-text(a2blckLayer)',

    // This rule was converted successfully to "HTML rule"
    '24.hu##^script:has-text(a2blckLayer)',
];

for (const testRule of testRules) {
    // issue: Conversion doesn't work in all cases
    const converted = RuleConverter.convertRule(testRule)[0];
    const rule = RuleFactory.createRule(converted, 0);
    if (rule instanceof CosmeticRule) {
        console.log(rule.getType(), rule.getText());
    }
}
```

Given output:
```powershell
D:\tsurlfiltertest>yarn --silent ts-node-esm --swc orderer.ts
0 entrepelis.org,mangagenki.me##^script[data-cfasync]:has-text(h=decodeURIComponent)
0 mangaraw.org##^script[data-cfasync]:has-text(D4zz.)
0 24.hu##^body > script:has-text(a2blckLayer)
3 24.hu$$script[tag-content="a2blckLayer"][max-length="262144"]
```

## References:
- Rule types: https://github.com/AdguardTeam/tsurlfilter/blob/8ae91ae82ab244de330d6ecf33197e63eb433968/packages/tsurlfilter/src/rules/cosmetic-rule.ts#L24
- uBlock HTML filters docs: https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#html-filters

**Comment by ameshkov** [comment]
@maximtop assigned to the v4.1 milestone.

* `entrepelis.org,mangagenki.me##^script[data-cfasync]:has-text(h=decodeURIComponent)` - this one should be successfully converted to HTML rule: `entrepelis.org,mangagenki.me$$script[data-cfasync][tag-content="h=decodeURIComponent"]`
* `mangaraw.org##^script[data-cfasync]:has-text(D4zz.)` - this should also be successfully converted to `mangaraw.org$$script[data-cfasync][tag-contains="D4zz."]`
* `24.hu##^body > script:has-text(a2blckLayer)` - this should be discarded since AG HTML filtering rules do not support selectors with combinators.

Note, that HTML filtering rules use a different way to escape doublequotes ('""' instead of `"`).

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#html-filtering-rules
